# Generated by Django 5.2.6 on 2025-10-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('street_number', models.TextField()),
                ('street_name', models.TextField()),
                ('apt_number', models.TextField()),
                ('zip_code', models.CharField(blank=True, max_length=5)),
                ('dob', models.TextField()),
                ('date_of_registration', models.TextField()),
                ('party_affilitation', models.CharField(blank=True, max_length=2)),
                ('precinct_number', models.CharField(blank=True, max_length=3)),
                ('v20state', models.BooleanField(default=False)),
                ('v21town', models.BooleanField(default=False)),
                ('v21primary', models.BooleanField(default=False)),
                ('v22general', models.BooleanField(default=False)),
                ('v23town', models.BooleanField(default=False)),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
